"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Component/Header";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [logo, setlogo] = useState("logo");
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header Username={logo} />
        {children}
      </body>
    </html>
  );
}
